version: '3.8'

services:
  app:
    build: .
    container_name: spsingla-app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app              # <-- Mount current folder into /app inside container
      - /app/node_modules   # <-- Avoid overwriting node_modules inside container
    command: nodemon --legacy-watch server.js
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_NAME: sp-singla-local
      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sp-singla-local
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
